# Generated by Django 4.2.2 on 2023-07-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='bajada',
            new_name='subtitulo',
        ),
    ]
